[package]
name = "roguelike"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.0"
avian2d = "0.4"
bevy_ecs_ldtk = "0.13.0"
bevy_window = "0.18.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
